---
title: "SPYTrade v1.1"
author: "Akbar Rizqiansyah"
date: "06/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyquant)
library(tidyverse)
library(ggplot2)
library(e1071)
library(lubridate)
library(SharpeR)
library(PortfolioAnalytics)
library(tbl2xts)
library(ROI)
library(plotly)
library(naniar)
library(broom)
library(quantmod)
library(rugarch)
library(rmgarch)
```

```{r, message = FALSE, echo = FALSE, warning = FALSE}
ticker <- read_csv("data/SPYticker.csv")

start = '2017-01-01'

```

```{r}
spy <- tq_get("SPY",
              from = start,
              to = today(),
              get = "stock.prices")
```

```{r, message = FALSE, echo = FALSE, warning = FALSE}
all_stock <- tq_get(ticker,
              from = start,
              to = today(),
              get = "stock.prices")
```

```{r}
write_csv(all_stock, "data/df0.csv")
```

```{r}
all_stock <- read_csv("data/df0.csv")
```

```{r}
#Subset data into training and verification
#verification data from today - 365 days

spy_train <- spy %>% filter(date < today()-days(365))
all_stock_train <- all_stock %>% filter(date<today()-days(365))

spy_verify <- spy %>% filter(date >= today()-days(365))
all_stock_verify <- all_stock %>% filter(date >= today()-days(365))

```

# Model Mondays return ARIMA + GARCH
# Select stocks of interest

```{r}
ticker = c("AAPL",
           "MSFT")

spy1 <- spy_train %>%
  mutate(day = wday(date, label = TRUE)) %>%
  filter(day == "Mon") %>%
  select("date", "symbol", "close") %>%
  mutate(r5_mon = log(close / lag(close, n =1 ))) %>%
  na.omit()
  

df1 <- all_stock_train %>%
  mutate(day = wday(date, label = TRUE)) %>%
  filter(symbol %in% ticker) %>%
  filter(day == "Mon") %>%
  select("date", "symbol", "close") %>%
  mutate(r5_mon = log(close / lag(close, n =1 )))

#Delete first date b/c the log return should be invalid
df1 <- df1 %>%
  anti_join(df1 %>% group_by(symbol) %>% summarise(min_date = min(date)),
            by = c("symbol" = "symbol", "date" = "min_date"))

```


```{r}
p_df1 <- ggplot(df1,
       aes(x= date,
           y= r5_mon,
           color= symbol)) + 
  geom_line()

ggplotly(p_df1)
#p_df1

ggplot(df1)+
  geom_histogram(aes(x= r5_mon, group_by= symbol))
```

```{r}
ARMA_BEST_FIT_FN <- function(data, ticker, maxp, maxq){
  df <- data %>% filter(symbol %in% ticker)
  xts1 <- tbl_xts(filter(df, date > ymd(start) + days(2)), 
                cols_to_xts = r5_mon, 
                spread_by= symbol)
  
  print("ARMA search for best model based on AIC")
  p = c(1:maxp)
  q = c(1:maxq)
  
  
  ARMA_tbl <- tibble(p = c(0),
                    q = c(0),
                    AIC = c(0),
                    BIC = c(0))
  for (i in p){
    for (j in q){
      print(paste("p =", i, ", q =", j))
      ug_spec <- ugarchspec(mean.model = list(armaOrder = c(i, j)))
      ugfit <- ugarchfit(spec = ug_spec, data = xts1)
      
      AIC <- infocriteria(ugfit)[1]
      BIC <- infocriteria(ugfit)[2]
      result <- tibble(p = i, q = j, AIC = AIC, BIC = BIC)
      ARMA_tbl <- bind_rows(ARMA_tbl, result)
    }
  }
  return(ARMA_tbl)
}
```

```{r}
aapl_arma <- ARMA_BEST_FIT_FN(data = df1, ticker = "AAPL", maxp = 5, maxq = 5)
```


```{r}
best_aapl_arma <- aapl_arma %>% top_n(1, -AIC)
df <- df1 %>% filter(symbol %in% c("AAPL"))
xts1 <- tbl_xts(filter(df, date > ymd(start) + days(2)), 
              cols_to_xts = r5_mon, 
              spread_by= symbol)
ug_spec <- ugarchspec(mean.model = list(armaOrder = c(best_aapl_arma$p, best_aapl_arma$q)))
ugfit <- ugarchfit(spec = ug_spec, data = xts1)

fitted_aapl <- tibble(fitted = ugfit@fit$fitted.values)
resid_aapl <- tibble(resid = ugfit@fit$residuals)

fitted_aapl <- df1 %>% filter(symbol == "AAPL") %>%
  select(date, r5_mon) %>%
  bind_cols(fitted_aapl, resid_aapl) %>%
  pivot_longer(cols = c(r5_mon, fitted),
               names_to = "type",
               values_to = "value")

ggplot(fitted_aapl) +
  geom_line(aes(x=date,
                y=value,
                color=type))

ggplot(fitted_aapl) +
  geom_line(aes(x=date,
                y=resid))
```
